// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv0dHtM5Qhdlywws5WLW-Wc-fN8K2iSkE',
    appId: '1:755773183987:android:c58378e92a97276d93e486',
    messagingSenderId: '755773183987',
    projectId: 'egrocer-457a9',
    storageBucket: 'egrocer-457a9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0Bo2AY6yqfCbJKvLYybAKIjHCLSFS6e8',
    appId: '1:755773183987:ios:d2621a585082bf1c93e486',
    messagingSenderId: '755773183987',
    projectId: 'egrocer-457a9',
    storageBucket: 'egrocer-457a9.appspot.com',
    androidClientId:
        '755773183987-42d5161052q353fslbqssggfstbt0dqp.apps.googleusercontent.com',
    iosClientId:
        '755773183987-94rmtbdu1krrnb9jlr3mleht9e7gtb3o.apps.googleusercontent.com',
    iosBundleId: 'com.wrteam.egrocer',
  );
}
